export const Routes = {
  DASHBOARD: "dashboard",
  ADMIN: "admin",
  LOGIN: "login",
  USER: "user",
  TOPUP: "topup",
  CREATE: "create",
  EDIT: "edit",
  TRANSFER: "transfer",
  AUTH: "auth",
  REWARD: "reward",
  HOME: "home",
  REGISTER: "register",
  STORE: "store",
  CATEGORY: "category",
  CART: "cart",
  PRODUCT: "product",
  CHECKOUT: "checkout",
  CONTACT: "contact",
  BLOG: "blog",
  DETAIL: "detail",
  SUB: "sub",
};
