export const tableFields = {
  CATEGORY_STORE: [
    {
      key: "action",
      label: "",
      _style: "min-width:220px",
      sorter: true,
      filter: false,
    },
    {
      key: "categoryID",
      label: "CategoryID",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "name",
      label: "Category Name",
      _style: "min-width:200px",
      sorter: true,
      filter: true,
    },
    {
      key: "totalProduct",
      label: "Total Product",
      _style: "min-width:200px",
      sorter: true,
      filter: true,
    },
    {
      key: "description",
      label: "Description",
      _style: "min-width:100px",
      sorter: true,
      filter: true,
    },
    {
      key: "createdAt",
      label: "Created At",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
  ],
  SUB_CATEGORY_STORE: [
    {
      key: "action",
      label: "",
      _style: "min-width:220px",
      sorter: true,
      filter: false,
    },
    {
      key: "categoryID",
      label: "CategoryID",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "subCategoryID",
      label: "subCategoryID",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "name",
      label: "Name",
      _style: "min-width:200px",
      sorter: true,
      filter: true,
    },
    {
      key: "totalProduct",
      label: "Total Product",
      _style: "min-width:200px",
      sorter: true,
      filter: true,
    },
    {
      key: "description",
      label: "Description",
      _style: "min-width:100px",
      sorter: true,
      filter: true,
    },
    {
      key: "createdAt",
      label: "Created At",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
  ],
  PRODUCT: [
    {
      key: "action",
      label: "",
      _style: "min-width:220px",
      sorter: true,
      filter: false,
    },
    {
      key: "productID",
      label: "productID",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "name",
      label: "Name",
      _style: "min-width:200px",
      sorter: true,
      filter: true,
    },
    {
      key: "description",
      label: "Description",
      _style: "min-width:100px",
      sorter: true,
      filter: true,
    },
    {
      key: "quantity",
      label: "quantity",
      _style: "min-width:100px",
      sorter: true,
      filter: true,
    },
    {
      key: "categoryID",
      label: "CategoryID",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "subCategoryID",
      label: "subCategoryID",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "price",
      label: "Price",
      _style: "min-width:200px",
      sorter: true,
      filter: true,
    },
    {
      key: "minPrice",
      label: "minPrice",
      _style: "min-width:200px",
      sorter: true,
      filter: true,
    },
    {
      key: "photos",
      label: "photos",
      _style: "min-width:100px",
      sorter: true,
      filter: true,
    },
    {
      key: "type",
      label: "type",
      _style: "min-width:100px",
      sorter: true,
      filter: true,
    },
    {
      key: "tag",
      label: "tag",
      _style: "min-width:100px",
      sorter: true,
      filter: true,
    },
    {
      key: "origin",
      label: "origin",
      _style: "min-width:100px",
      sorter: true,
      filter: true,
    },
    {
      key: "trademark",
      label: "trademark",
      _style: "min-width:100px",
      sorter: true,
      filter: true,
    },
    {
      key: "createdAt",
      label: "Created At",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "updatedAt",
      label: "Updated At",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
  ],
};
