export const tableFields = {
  USER_ADMIN: [
    {
      key: "action",
      label: "",
      _style: "min-width:220px",
      sorter: true,
      filter: false,
    },
    {
      key: "id",
      label: "ID",
      _style: "min-width:80px",
      sorter: true,
      filter: true,
    },
    {
      key: "username",
      label: "Tên tài khoản",
      _style: "min-width:200px",
      sorter: true,
      filter: true,
    },
    {
      key: "fullname",
      label: "Tên đầy đủ",
      _style: "min-width:200px",
      sorter: true,
      filter: true,
    },
    {
      key: "avatar",
      label: "Ảnh đại diện",
      _style: "min-width:100px",
      sorter: true,
      filter: true,
    },
    {
      key: "phone_number",
      label: "Số điện thoại",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "email",
      label: "Email",
      _style: "min-width:200px",
      sorter: true,
      filter: true,
    },
    {
      key: "birthday",
      label: "Ngày sinh",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "current_point",
      label: "Point hiện tại",
      _style: "min-width:130px",
      sorter: true,
      filter: true,
    },
    {
      key: "status",
      label: "Trạng thái",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
  ],
  TOPUP: [
    {
      key: "action",
      label: "",
      sorter: false,
      filter: false,
    },
    {
      key: "id",
      label: "ID",
      _style: "min-width:80px text-align: center",
      sorter: true,
      filter: true,
    },
    {
      key: "transaction_id",
      label: "Mã giao dịch",
      _style: "min-width:150px; text-align: center",
      sorter: true,
      filter: true,
    },
    {
      key: "username",
      label: "Username",
      _style: "min-width:150px; text-align: center",
      sorter: true,
      filter: true,
    },
    {
      key: "fullname",
      label: "Tên đầy đủ",
      _style: "min-width:200px; text-align: center",
      sorter: true,
      filter: true,
    },
    {
      key: "amount",
      label: "Số lượng",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "point_before",
      label: "Point trước khi nạp",
      _style: "min-width:180px; text-align: center",
      sorter: true,
      filter: true,
    },
    {
      key: "point_after",
      label: "Point sau khi nạp",
      _style: "min-width:180px; text-align: center",
      sorter: true,
      filter: true,
    },
    {
      key: "message",
      label: "Message",
      _style: "min-width:150px; text-align: center",
      sorter: true,
      filter: true,
    },
    {
      key: "created_at",
      label: "Thời gian",
      _style: "min-width:150px; text-align: center",
      sorter: true,
      filter: true,
    },
  ],
  REWARD: [
    {
      key: "action",
      label: "",
      sorter: false,
      filter: false,
    },
    {
      key: "id",
      label: "ID",
      _style: "min-width:80px text-align: center",
      sorter: true,
      filter: true,
    },
    {
      key: "transaction_id",
      label: "Mã giao dịch",
      _style: "min-width:150px; text-align: center",
      sorter: true,
      filter: true,
    },
    {
      key: "username",
      label: "Username",
      _style: "min-width:150px; text-align: center",
      sorter: true,
      filter: true,
    },
    {
      key: "fullname",
      label: "Tên đầy đủ",
      _style: "min-width:200px; text-align: center",
      sorter: true,
      filter: true,
    },
    {
      key: "amount",
      label: "Số lượng",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "message",
      label: "Message",
      _style: "min-width:150px; text-align: center",
      sorter: true,
      filter: true,
    },
    {
      key: "created_at",
      label: "Thời gian",
      _style: "min-width:150px; text-align: center",
      sorter: true,
      filter: true,
    },
  ],
  TRANSFERPOINT: [
    {
      key: "action",
      label: "",
      _style: "min-width:50px",
      sorter: true,
      filter: false,
    },
    {
      key: "id",
      label: "ID",
      _style: "min-width:50px; text-align:center",
      sorter: false,
      filter: false,
    },
    {
      key: "transaction_id",
      label: "Mã giao dịch",
      _style: "min-width:100px; text-align:center",
      sorter: true,
      filter: true,
    },
    {
      key: "sender_username",
      label: "Người gửi",
      _style: "min-width:200px; text-align:center",
      sorter: true,
      filter: true,
    },
    {
      key: "sender_fullname",
      label: "Người gửi(Tên đầy đủ)",
      _style: "min-width:200px; text-align:center",
      sorter: true,
      filter: true,
    },
    {
      key: "receiver_username",
      label: "Người nhận",
      _style: "min-width:200px; text-align:center",
      sorter: true,
      filter: true,
    },
    {
      key: "receiver_fullname",
      label: "Người nhận(Tên đầy đủ)",
      _style: "min-width:200px; text-align:center",
      sorter: true,
      filter: true,
    },
    {
      key: "amount",
      label: "Số Point giao dịch",
      _style: "min-width:100px; text-align:center",
      sorter: true,
      filter: true,
    },
    {
      key: "created_at",
      label: "Ngày giao dịch",
      _style: "min-width:100px; text-align:center",
      sorter: true,
      filter: true,
    },
  ],
  NEWS: [
    {
      key: "action",
      label: "",
      _style: "min-width:100px",
      sorter: true,
      filter: false,
    },
    {
      key: "id",
      label: "ID",
      _style: "min-width:50px; text-align:center",
      sorter: true,
      filter: true,
    },
    {
      key: "title",
      label: "Tiêu đề",
      _style: "min-width:200px; text-align:center",
      sorter: true,
      filter: true,
    },
    {
      key: "content",
      label: "Nội dung",
      _style: "min-width:200px; text-align:center",
      sorter: true,
      filter: true,
    },
    {
      key: "created_at",
      label: "Thời gian",
      _style: "min-width:100px; text-align:center",
      sorter: true,
      filter: true,
    },
  ],
  NOTIFICATION: [
    {
      key: "action",
      label: "",
      _style: "min-width:100px",
      sorter: true,
      filter: false,
    },
    {
      key: "id",
      label: "ID",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "title",
      label: "Tiêu đề",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "content",
      label: "Nội dung",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
    {
      key: "avatar",
      label: "Hình ảnh",
      _style: "min-width:150px",
      sorter: false,
      filter: true,
    },
    {
      key: "created_at",
      label: "Thời gian",
      _style: "min-width:150px",
      sorter: true,
      filter: true,
    },
  ],
};
