export const Urls = {
  BASE_URL_SERVER_1: "http://localhost:3000/",
  LOGIN: "login",
  LOGOUT: "logout",
  USERS: "users",
  AUTH: "auth",
  ADMIN: "admin",
  CREATE: "create",
  EDIT: "edit",
  UPDATE: "update",
  DELETE: "delete",
  UPDATE_STATUS: "update-status",
  TRANSFERPOINT: "transferpoint",
  TOPUP: "topup",
  LIST: "list",
  NEWS: "news",
  DETAIL: "detail",
  REWARD: "reward",
  STORE_TOKEN: "store-token",
  NOTIFICATION: "notification",
  IMG_NULL:
    "http://localhost:8000/storage/static/avatar/user/no-avatar/no-avatar.png",
  HOME: "home",
  REGISTER: "register",
  STORE: "store",
  STORES: "stores",
};
