export const badRequestErrors = {
  UserAlreadyExisted: 'User already exists',
  UserAccessAlreadyExists: 'UserAccess already exists',
  RoleAlreadyExists: 'User Role already exists',
  UserStatusIsInActive: 'User Status Is InActive',
  RoleDoesNotMatch: `User Role doesn't match`,
  QuantityOfProductNotMatch: 'Quantity of product not match',
  EmailDoesNotMatch: `Email doesn't match`,
  DoNotRepeatProductIDInOrder: 'Do not repeat productId in order',
  ValidationError: 'Validation Error',
  OrderProductsDontExist: `OrderProducts don't Exist`,
  OrderProductsExisted: 'OrderProducts Existed',
  TransactionDoesNotMatch: `Transaction doesn't match`,
  OrderDoesNotMatch: `Order doesn't match`,
};

export const notFoundErrors = {
  StoreNotFound: 'Store is not found',
  PermissionNotFound: 'Permission is not found',
  UserNotFound: 'User is not found',
  UserAccessNotFound: 'UserAccess is not found',
  ExtendedUserNotFound: 'ExtendUser is not found',
  CategoryNotFound: 'Category is not found',
  SubCategoryNotFound: 'SubCategory is not found',
  ProductNotFound: 'Product is not found',
  EmailNotFound: 'Email is not found',
  OrderNotFound: 'Order is not found',
  OrderLogNotFound: 'OrderLog is not found',
  OrderProductNotFound: 'OrderProduct is not found',
  NotificationNotFound: 'Notification is not found',
  TransactionNotFound: 'Transaction is not found',
  TransactionLogsNotFound: 'TransactionLog is not found',
};
