export enum StatusTransactions {
  CUSTOMER_ACCEPTED = 'CUSTOMER_ACCEPTED',
  PENDING = 'PENDING',
  CUSTOMER_CANCELED = 'CUSTOMER_CANCELED',
  DENIED = 'DENIED',
  PROCESSING = 'PROCESSING',
  FINISHED = 'FINISHED',
}
